import React from 'react'

export const tooltips = {
  ciq: {
    initiation: {
      customerType: 'Partners are resellers of your product whereas organizations are consumers.',
      businessName: 'The name of the customer’s business. Min length is 3. Max length is 180.',
      domain: 'Root domain (i.e. mycompany.com). Once set this cannot be changed.',
      accountPrime: 'Account Prime of your Business. Max length is 50.',
      plmPrimeId: 'PLM Prime of your Business.',
      operationPrimeId: 'Operation Prime of your Business.',
    },
    primaryContactName: 'Max length of Primary Contact name is 50. If Primary Contact Name is left empty, it will take the first 50 chars of Business Name.',
    primaryContactEmail: 'Primary contact e-mail. This will be used to notify the customer of their account creation. Max length is 100.',
    customerIdentifier: 'Customer specific identifier to be added to invoices to aid in downstream bill correlation (free form). Max length is 128.',
    currency: 'Customer\'s currency preference based on available catalogs.',
    supplierCatalog: 'The catalog associated with the customer.',
    maxOrderValue: 'The maximum net order value per month.',
    billing: 'Disable only if you do not want to generate any invoices for this Customer.  Once set this cannot be changed.',
    billingModel: 'Forward bills in advance each month.  Arrears bills at the end of the month.  All customers of this partner will inherit the same value. Once set this cannot be changed.',
    billingType: 'For new top level Partners, "Billing Type" can be changed as long as they don\'t have any children.',
    prorating: 'If enabled, the customer will be billed for the remainder of the month for any orders fulfilled after the last billing date.',
    minCommit: 'If enabled, the customer will be billed for a minimum value if actual usage is lower.',
    minCommitValue: 'The minimum required net order value per month.',
    minCommitStart: 'The date on which the minimum commitment becomes effective.',
    autoAcceptance: 'If enabled incoming orders from this customer are automatically accepted if funds are available.',
    orderNotification: 'Disable auto approved order notices.',
    dnsBranding: 'Allow the customer to use their own FQDN branding for server addresses.',
    pstnManagement: 'If enabled then customer can manage their own PSTN DIDs. Once set this cannot be changed. Top-level partners will always have this set to enabled.',
    portalBranding: 'Allow customer to brand their portal instance.  Default is enabled for Partners.  Once set this cannot be changed.',
    sftpTransfer: 'If Dedicated is set then customer can manage their own SFTP. If Inherited is set, the customer inherits their service provider’s settings for SFTP Transfer and does not see the SFTP Transfer tab.',
    clientManagement: 'If enabled, allows customer to manage client branding and deployment configuration. If disabled, customer inherits configuration from parent.',
    eupLanguage: 'End User Portal language of services.',
    adminLanguage: 'Admin Portal language of services.',
    mandatorySiteAddress: 'Determines whether site address is mandatory.',
    singleSignOn: 'Permits this group to configure Single Sign-on. Please contact your support team for modifications.',
    classificationType: 'Select a customer type.',
    timezone: 'Select Timezone of services.',
    minCharacters: 'Min is 0, max is 10.',
    minDigits: 'Min is 0, max is 10.',
    minLength: 'Min is 8, max is 16.',
    initReset: 'Requires users to login to the End User Portal (EUP) and reset their password before registering with a client. If you are using PMC passwords, the suggestion is to force a password reset for the non-PMC password.',
    preventPreviousPassword: 'Prevent Previous Password.',
    enablePropertyFiltering: 'Enable Property Filtering.',
    minCapitalLetters: 'Min is 0, max is 10.',
    minSpecialCharacters: 'Min is 0, max is 10.',
    maxFailedLogin: 'Min is 0, max is 10',
    lockoutDuration: 'Provide Lockout Duration in seconds.',
    brandedUrls: {
      Portal: 'The KBS Admin Portal URL is used by Partners and optionally by their customers to manage features provided to them by the service.',
      EndUserPortal: 'The KBS End User Portal is used by end users to manage features provided to them by the service ',
      SmartOfficeCollab: 'The Smart Office Collaboration Video Conferencing and Screen Sharing services require a URL that the end user will use to access their collaboration room.',
      WebClient: 'The Client API URL is used by end users to login to the Web Client from a browser.',
      VoiceMailPortal: 'The Voicemail URL is used by end users to manage features provided to them by the service.',
      SIPProxy: 'The SIP Proxy Address is used by client devices to register with KBS SBC',
      brandedUrl: 'URL of the Branded URL',
      ipAddress: 'IP Address that the FQDNs should resolve to.  Before URLs can be used, the partner will need to update the DNS of the FQDN as well as order an SSL certificate to be able to utilize the custom branded URL.',
      ssl: {
        division: 'Division',
        organization: 'Organization Name',
        locality: ' Location of the Organization',
        state: 'State of the Organization',
        country: 'Country of the Organization',
        email: <><p>An Email address must be provided which the certificate authority will send an approval email to, there will be a link in the email that will be used to verify domain ownership.</p><br></br><p>Approver Email should be one of the following addresses:</p> <p>webmaster@&lt;domain&gt;.com</p> <p>postmaster@&lt;domain&gt;.com</p> <p>hostmaster@&lt;domain&gt;.com</p> <p>administrator@&lt;domain&gt;.com</p> <p>admin@&lt;domain&gt;.com</p></>,
      },
    },
    accessNumbers: {
      pstnDid: 'Directory Number from your provider',
      location: 'Location of the number to easily group the numbers when you have multiple locations.',
      alias: 'Enter any alisases (internal number) numbers that you want to use for accessing MeetMe, Voicemail, Call Grabber services.',
      assignmentOrUse: 'DiD used for a users account (You will assign them to users from the portal during user provisioning)',
      meetMe: 'PSTN Access to the conferencing server, to remotely access conferencing and for outside parties to join conferences',
      voicemail: 'PSTN Access to the voicemail server to remotely retrieve messages',
      smartOfficeCollaboration: 'PSTN Access to the collaboration server, to remotely access sessions and for outside parties to join collaboration sessions.',
      callGrabber: 'DiD used to access the call grabber feature from a PSTN phone (Required for GENCom Mobile Call Grabber)',
      nuviaOperations: 'DiD reserved for NUViA operations testing',
      emergencyAIN: 'This is used on the ER tab, and these numbers can be used to designate each location to a PSAP for E911',
      other: 'For uses not defined above',
    },
    serviceNode: {
      serviceNodeName:'Name for the service node',
      pstnProvider: 'This is the service provider that will be providing the DiDs used for your service.',
      contactName: 'Contact Name',
      contactNumber: 'Contact Number',
      ipAddress: <><p>The IP address that the vendor will be routing calls from and receiving calls to.</p></>,
      location: 'Location',
      equipment: 'Typically, this is either a SBC, SIP Enabled PBX or a PRI gateway',
      vendorOrModel: 'Vendor/Model',
    },
    logicalGroups: {
      entityName: <><p>For the telephony routes, you will have the option of sending to a specific route, or using a logical entity to provide alternate routes if there is a problem routing to an endpoint.</p></>,
      serviceNode: 'The Service Nodes are defined above.',
    },
    telephonyRoutes: {
      name: 'The name of the Telephony Route.  Maximum of 20 characters in length.  This should usually be descriptive enough so that you know what the route does based on the name.',
      description: 'A description for this telephony route. A maximum of 100 characters in length.  This should be a summary of what the route does.',
      fromDigits: <><p>This, along with &quot;To Digits&quot; determines the range of numbers that will use this PSTN Telephony Route.</p></>,
      toDigits: <><p>This, along with "From Digits" determines the range of numbers that will use this PSTN Telephony Route.</p></>,
      minDigits: <><p>The number to be translated should have digits equal to or more than the Min Number of Digits parameter value. This value must not be less than the number of digits in the From Digits field.</p></>,
      maxDigits:<><p>The number to be translated should have digits equal to or more than the Min Number of Digits parameter value. This value must not be less than the number of digits in the From Digits field.</p></>,
      remove: 'This is the number of leading digits to be removed prior to routing the call.  For example, if Remove is set to 2, it will remove the first 2 digits of the dialed number.',
      prefix: 'The value entered here will be prefixed to the dialed number before routing.  The prefix will occur after "Remove" has been performed.\n',
      classOfServices: <><p>This is the class of service to be assigned to this route. The class of service levels should have been defined in the "COS" tab. The value entered here is the minimum value required in order to make this call.</p></>,
      logicalEntity: 'The service node or logical entity, as defined in the "Nodes" tab, where this call should route.  A service node is a single endpoint and the call will be routed specifically to that endpoint.',
      overrideName: 'By default, a users public charge id, which is defined when the user is created, is used for caller ID on outgoing PSTN calls.  NUViA provides the ability to override both the caller ID and the calling name display. Overriding the caller id / calling name on a telephony route will send the number and name defined as the override number and name on outgoing calls.',
      overrideValue: 'By default, a users public charge id, which is defined when the user is created, is used for caller ID on outgoing PSTN calls.  NUViA provides the ability to override both the caller ID and the calling name display. Overriding the caller id / calling name on a telephony route will send the number and name defined as the override number and name on outgoing calls.',
      overrideChargeId: 'By default, a users public charge id, which is defined when the user is created, is used for caller ID on outgoing PSTN calls.  NUViA provides the ability to override both the caller ID and the calling name display. Overriding the caller id / calling name on a telephony route will send the number and name defined as the override number and name on outgoing calls.',
      overrideChargeIdValue: 'By default, a users public charge id, which is defined when the user is created, is used for caller ID on outgoing PSTN calls.  NUViA provides the ability to override both the caller ID and the calling name display. Overriding the caller id / calling name on a telephony route will send the number and name defined as the override number and name on outgoing calls.',
    },
  },
}
